In [7]:
import csv
import cv2
from pytesseract import pytesseract

In [45]:
filename = '/home/saumya/Desktop/FreeUKGen/Probate Parsing/1873 Probate/1873 Probate A/00004.jpg'

In [3]:
img = cv2.imread(filename)
h, w, _ = img.shape

In [5]:
cv2.imwrite("hello.jpg", img)

True

In [8]:
boxes = pytesseract.image_to_boxes(img)

In [9]:
print(boxes)

m 156 3847 199 3863 0
w 199 3842 228 3860 0
b 243 3847 258 3864 0
y 259 3842 274 3860 0
F 289 3847 303 3863 0
u 304 3847 332 3860 0
e 333 3847 347 3860 0
fi 347 3847 376 3864 0
m 377 3847 407 3863 0
“ 537 2951 600 3032 0
T 597 2998 619 3029 0
I 623 2972 660 3030 0
L 663 2973 716 3031 0
L 719 2973 771 3034 0
S 776 2974 813 3034 0
A 882 2984 916 3022 0
N 921 2985 952 3023 0
D 957 2985 991 3023 0
A 1060 2981 1121 3039 0
D 1122 2983 1182 3042 0
M 1184 2985 1257 3045 0
I 1259 2986 1298 3045 0
N 1300 2987 1361 3072 0
I 1365 2989 1402 3048 0
S 1407 2990 1445 3048 0
T 1448 2991 1498 3050 0
R 1500 2992 1559 3052 0
A 1560 2994 1622 3052 0
T 1622 2996 1673 3055 0
I 1674 2996 1712 3056 0
O 1716 2998 1769 3058 0
N 1773 2999 1835 3059 0
S 1841 3001 1879 3060 0
. 1887 3002 1899 3015 0
m 266 2412 332 2449 0
B 334 2413 366 2449 0
A 367 2414 401 2449 0
T 404 2415 435 2450 0
T 439 2415 472 2453 0
E 493 2416 526 2451 0
fi 528 2417 558 2452 0
z 559 2419 578 2443 0
a 581 2419 605 2445 0
b 603 2420 629 2454 0


In [14]:
for b in boxes.splitlines():
    b = b.split(' ')
    print(b[0])
    img = cv2.rectangle(img, (int(b[1]), h - int(b[2])), (int(b[3]), h - int(b[4])), (0, 255, 0), 2)

m
w
b
y
F
u
e
fi
m
“
T
I
L
L
S
A
N
D
A
D
M
I
N
I
S
T
R
A
T
I
O
N
S
.
m
B
A
T
T
E
fi
z
a
b
e
t
h
.
E
fl
e
fi
s
m
d
e
r
£
3
0
0
.
A
B
B
E
Y
A
m
B
M
n
g
h
a
m
.
-
M
e
c
t
s
u
n
d
e
r
£
7
0
0
.
A
B
B
E
Y
E
d
m
m
d
Y
o
r
k
.
E
E
M
S
m
d
e
r
£
6
0
0
.
l
-
,
‘
A
B
B
E
Y
E
a
M
e
t
C
a
t
h
e
m
e
.
‘
'
m
m
u
d
e
r
£
4
5
0
.
V
A
B
B
E
Y
M
a
n
.
‘
H
M
S
m
a
r
£
4
,
W
.
1
8
7
3
.
4
J
u
n
e
.
A
d
m
i
n
i
s
t
i
'
a
t
i
o
n
o
f
t
h
e
e
fi
e
c
t
s
o
f
E
l
i
z
a
b
e
t
h
A
b
h
a
t
t
l
a
t
e
o
f
A
s
t
l
e
y
B
a
n
k
B
o
l
t
o
n
i
n
t
h
e
C
o
u
r
i
t
y
o
f
L
a
n
c
a
s
t
e
r
W
i
d
o
w
\
v
h
o
d
i
e
d
1
9
M
a
r
c
h
1
8
7
3
a
t
B
o
l
t
o
n
w
a
s
g
r
a
n
t
e
d
a
t
M
a
n
c
h
e
s
t
e
r
t
o
W
i
l
l
i
a
m
A
b
b
a
t
t
o
f
B
i
'
e
i
g
h
t
m
e
t
-
s
t
r
e
e
t
B
o
l
t
o
n
S
k
i
p
M
a
n
u
f
a
c
t
u
r
e
r
t
h
e
S
o
n
a
n
d
o
n
e
o
f
t
h
e
N
e
x
t
o
f
K
i
n
.
I
3
O
c
t
o
b
e
r
.
T
h
e
W
i
l
l
o
f
A
n
n
B
u
r
r
i
n
g
h
a
m
A
b
b
e
y
l
a
t
e
o
f
A
p
p
l
e
b
y
i
n
t
h
e
C
o
u
n
t
y
o
f
me
o
l
n
S
p
i
n
s
t
e
r
w
h
o
d
i
e
d
7
S
e

In [11]:
cv2.imwrite("hello.jpg", img)

True

In [34]:
im = cv2.imread(filename)

In [35]:
gray=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
contours,hierarchy,_ = cv2.findContours(gray,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
idx =0 

In [36]:
for cnt in contours:
    idx += 1
    x,y,w,h = cv2.boundingRect(cnt)
    roi=im[y:y+h,x:x+w]
    cv2.rectangle(im,(x,y),(x+w,y+h),(200,0,0),2)

In [37]:
cv2.imwrite("hello1.jpg", img)

True

In [ ]:
import numpy as np 
 
# read and scale down image
img = cv2.pyrDown(cv2.imread(filename, cv2.IMREAD_UNCHANGED))
 
# threshold image
ret, threshed_img = cv2.threshold(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY),
                127, 255, cv2.THRESH_BINARY)
# find contours and get the external one
image, contours, hier = cv2.findContours(threshed_img, cv2.RETR_TREE,
                cv2.CHAIN_APPROX_SIMPLE)
 
# with each contour, draw boundingRect in green
# a minAreaRect in red and
# a minEnclosingCircle in blue
for c in contours:
    # get the bounding rect
    x, y, w, h = cv2.boundingRect(c)
    # draw a green rectangle to visualize the bounding rect
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
 
    # get the min area rect
    rect = cv2.minAreaRect(c)
    box = cv2.boxPoints(rect)
    # convert all coordinates floating point values to int
    box = np.int0(box)
    # draw a red 'nghien' rectangle
    cv2.drawContours(img, [box], 0, (0, 0, 255))
 
    # finally, get the min enclosing circle
    (x, y), radius = cv2.minEnclosingCircle(c)
    # convert all values to int
    center = (int(x), int(y))
    radius = int(radius)
    # and draw the circle in blue
    img = cv2.circle(img, center, radius, (255, 0, 0), 2)
 
print(len(contours))
cv2.drawContours(img, contours, -1, (255, 255, 0), 1)
 
cv2.imshow("contours", img)
 
ESC = 27
while True:
    keycode = cv2.waitKey()
    if keycode != -1:
        keycode &amp;= 0xFF
        if keycode == ESC:
            break
cv2.destroyAllWindows()


In [46]:
import cv2
import sys

SCALE = 4
AREA_THRESHOLD = 427505.0 / 2

def show_scaled(name, img):
    try:
        h, w  = img.shape
    except ValueError:
        h, w, _  = img.shape
    cv2.imwrite("1.jpg", cv2.resize(img, (w // SCALE, h // SCALE)))

def main():
    img = cv2.imread(filename)
    img = img[10:-10, 10:-10] # remove the border, it confuses contour detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    show_scaled("original", gray)

    # black and white, and inverted, because
    # white pixels are treated as objects in
    # contour detection
    thresholded = cv2.adaptiveThreshold(
                gray, 255,
                cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV,
                25,
                15
            )
    show_scaled('thresholded', thresholded)
    # I use a kernel that is wide enough to connect characters
    # but not text blocks, and tall enough to connect lines.
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (13, 33))
    closing = cv2.morphologyEx(thresholded, cv2.MORPH_CLOSE, kernel)

    im2, contours, hierarchy = cv2.findContours(closing, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnt = contours[0]
    
    show_scaled("closing", closing)

    for contour in contours:
        convex_contour = cv2.convexHull(contour)
        area = cv2.contourArea(convex_contour)
        epsilon = 0.1*cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour,epsilon,True)
        print("Contour = ",approx)
        if area > AREA_THRESHOLD:
            cv2.drawContours(img, [approx], -1, (255,0,0), 3)

    show_scaled("contours", img)
    cv2.imwrite("contours.png", img)

if __name__ == '__main__':
    main()

Contour =  [[[ 389 4275]]]
Contour =  [[[ 112 4253]]]
Contour =  [[[ 120 4257]]

 [[ 171 4275]]

 [[ 132 4242]]]
Contour =  [[[ 323 4236]]

 [[ 324 4241]]

 [[ 325 4239]]]
Contour =  [[[ 430 4227]]

 [[ 436 4230]]]
Contour =  [[[ 509 4213]]]
Contour =  [[[1285 4212]]]
Contour =  [[[1254 4209]]

 [[1254 4210]]

 [[1255 4210]]

 [[1255 4209]]]
Contour =  [[[1119 4208]]

 [[1119 4209]]

 [[1120 4209]]

 [[1120 4208]]]
Contour =  [[[1325 4204]]

 [[1325 4205]]]
Contour =  [[[1085 4198]]

 [[1085 4199]]]
Contour =  [[[ 544 4198]]]
Contour =  [[[1099 4190]]

 [[1104 4198]]]
Contour =  [[[ 622 4190]]

 [[ 622 4191]]]
Contour =  [[[1201 4184]]

 [[1202 4184]]]
Contour =  [[[1193 4179]]

 [[1194 4179]]]
Contour =  [[[1520 4177]]]
Contour =  [[[2286 4174]]

 [[2280 4182]]

 [[2286 4182]]]
Contour =  [[[1442 4173]]

 [[1443 4173]]]
Contour =  [[[1424 4172]]

 [[1424 4173]]

 [[1425 4173]]

 [[1425 4172]]]
Contour =  [[[1446 4171]]

 [[1451 4172]]]
Contour =  [[[1152 4168]]]
Contour =  [[[1224 416

Contour =  [[[ 442 2884]]

 [[ 442 2890]]

 [[ 444 2890]]

 [[ 445 2887]]]
Contour =  [[[ 870 2883]]

 [[ 890 2881]]]
Contour =  [[[ 531 2880]]

 [[ 534 2882]]

 [[ 534 2880]]]
Contour =  [[[ 587 2879]]

 [[ 586 2881]]

 [[ 590 2883]]

 [[ 590 2879]]]
Contour =  [[[1017 2878]]

 [[1016 2878]]

 [[1015 2880]]

 [[1016 2880]]]
Contour =  [[[ 566 2878]]

 [[ 566 2880]]

 [[ 569 2879]]

 [[ 569 2878]]]
Contour =  [[[1038 2877]]

 [[1049 2877]]]
Contour =  [[[ 630 2876]]

 [[ 636 2905]]]
Contour =  [[[ 712 2874]]

 [[ 712 2876]]

 [[ 719 2876]]

 [[ 716 2873]]]
Contour =  [[[1027 2873]]

 [[1027 2874]]

 [[1030 2874]]

 [[1029 2872]]]
Contour =  [[[ 833 2871]]

 [[ 834 2873]]

 [[ 836 2873]]

 [[ 835 2871]]]
Contour =  [[[ 953 2870]]

 [[ 955 2869]]

 [[ 953 2869]]]
Contour =  [[[ 926 2869]]

 [[ 926 2871]]

 [[ 933 2870]]]
Contour =  [[[1059 2866]]

 [[1059 2869]]

 [[1063 2868]]

 [[1063 2866]]]
Contour =  [[[ 535 2864]]

 [[ 535 2867]]

 [[ 539 2866]]

 [[ 538 2864]]]
Contour =  [[[2486 

Contour =  [[[2736 2052]]

 [[2736 2056]]

 [[2738 2057]]

 [[2739 2052]]]
Contour =  [[[2637 2067]]

 [[2744 2129]]]
Contour =  [[[ 242 2052]]

 [[ 242 2053]]

 [[ 244 2053]]

 [[ 244 2052]]]
Contour =  [[[ 863 2051]]

 [[ 863 2053]]

 [[ 864 2053]]]
Contour =  [[[2422 2032]]]
Contour =  [[[2652 2024]]

 [[2647 2027]]

 [[2651 2028]]]
Contour =  [[[ 896 2017]]]
Contour =  [[[ 550 2007]]

 [[ 552 2033]]]
Contour =  [[[ 237 2001]]

 [[ 235 1999]]

 [[ 234 2002]]]
Contour =  [[[1050 1994]]]
Contour =  [[[ 280 1977]]

 [[ 280 1979]]

 [[ 282 1979]]]
Contour =  [[[ 897 1964]]

 [[ 898 1967]]

 [[ 899 1965]]]
Contour =  [[[ 894 1960]]

 [[ 895 1961]]

 [[ 895 1960]]]
Contour =  [[[ 841 1959]]

 [[ 841 1961]]

 [[ 843 1960]]]
Contour =  [[[ 814 1959]]

 [[ 816 1961]]

 [[ 816 1959]]]
Contour =  [[[ 678 1958]]

 [[ 678 1960]]]
Contour =  [[[ 230 1958]]]
Contour =  [[[ 770 1957]]

 [[ 770 1958]]]
Contour =  [[[ 616 1963]]

 [[ 635 1965]]

 [[ 623 1957]]]
Contour =  [[[ 571 1957]]

 [[ 573 1960